version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159357
      POSTGRES_DB: hakanton_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  nodeapp:
    build: . # Uses the Dockerfile in the project root
    working_dir: /app
    environment:
      - DB_NAME=hakanton_db
      - DB_USER=postgres
      - DB_PASSWORD=159357
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "3000:3000" # Map to your Node.js server's port
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped
    # No 'command:' needed (defined in Dockerfile)
    # No 'volumes:' for code (already copied in Dockerfile)
    # Add this if you need live code reloading in development:
    volumes:
      - .:/app
      - /app/node_modules # Prevent host/node_modules overwrite

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
