version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=159357
      - POSTGRES_DB=hakanton_db
      - POSTGRES_HOST_AUTH_METHOD=trust # This disables password authentication
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf # Optional: custom HBA config

  nodeapp:
    build: .
    working_dir: /app
    environment:
      - DB_NAME=hakanton_db
      - DB_USER=postgres
      - DB_PASSWORD=159357 # Can be removed if you want
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
