version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=159357
      - POSTGRES_DB=hakanton_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-network
    restart: unless-stopped

  nodeapp:
    build: .
    working_dir: /app
    environment:
      - DB_NAME=hakanton_db
      - DB_USER=postgres
      - DB_PASSWORD=159357
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
